package dicky.entities;
// Generated Mar 13, 2017 9:18:13 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kategori generated by hbm2java
 */
@Entity
@Table(name="kategori"
    ,catalog="demo_spring"
)
public class Kategori  implements java.io.Serializable {


     private String idKategori;
     private String nama;
     private Set<Product> products = new HashSet<Product>(0);

    public Kategori() {
    }

	
    public Kategori(String idKategori, String nama) {
        this.idKategori = idKategori;
        this.nama = nama;
    }
    public Kategori(String idKategori, String nama, Set<Product> products) {
       this.idKategori = idKategori;
       this.nama = nama;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id_kategori", unique=true, nullable=false, length=12)
    public String getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(String idKategori) {
        this.idKategori = idKategori;
    }

    
    @Column(name="nama", nullable=false, length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kategori")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


