package dicky.entities;
// Generated Mar 13, 2017 9:18:13 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersDetailId generated by hbm2java
 */
@Embeddable
public class OrdersDetailId  implements java.io.Serializable {


     private int idOrders;
     private String idProduct;

    public OrdersDetailId() {
    }

    public OrdersDetailId(int idOrders, String idProduct) {
       this.idOrders = idOrders;
       this.idProduct = idProduct;
    }
   


    @Column(name="id_orders", nullable=false)
    public int getIdOrders() {
        return this.idOrders;
    }
    
    public void setIdOrders(int idOrders) {
        this.idOrders = idOrders;
    }


    @Column(name="id_product", nullable=false, length=12)
    public String getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersDetailId) ) return false;
		 OrdersDetailId castOther = ( OrdersDetailId ) other; 
         
		 return (this.getIdOrders()==castOther.getIdOrders())
 && ( (this.getIdProduct()==castOther.getIdProduct()) || ( this.getIdProduct()!=null && castOther.getIdProduct()!=null && this.getIdProduct().equals(castOther.getIdProduct()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOrders();
         result = 37 * result + ( getIdProduct() == null ? 0 : this.getIdProduct().hashCode() );
         return result;
   }   


}


