package dicky.entities;
// Generated Mar 13, 2017 9:18:13 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersDetail generated by hbm2java
 */
@Entity
@Table(name="orders_detail"
    ,catalog="demo_spring"
)
public class OrdersDetail  implements java.io.Serializable {


     private OrdersDetailId id;
     private Product product;
     private Orders orders;
     private int quantity;
     private BigDecimal price;

    public OrdersDetail() {
    }

    public OrdersDetail(OrdersDetailId id, Product product, Orders orders, int quantity, BigDecimal price) {
       this.id = id;
       this.product = product;
       this.orders = orders;
       this.quantity = quantity;
       this.price = price;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOrders", column=@Column(name="id_orders", nullable=false) ), 
        @AttributeOverride(name="idProduct", column=@Column(name="id_product", nullable=false, length=12) ) } )
    public OrdersDetailId getId() {
        return this.id;
    }
    
    public void setId(OrdersDetailId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_product", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_orders", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=6, scale=3)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


