package dicky.entities;
// Generated Mar 13, 2017 9:18:13 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="demo_spring"
)
public class Product  implements java.io.Serializable {


     private String idProduct;
     private Kategori kategori;
     private String nameProduct;
     private BigDecimal price;
     private String filename;
     private byte[] filedata;
     private Set<OrdersDetail> ordersDetails = new HashSet<OrdersDetail>(0);

    public Product() {
    }

	
    public Product(String idProduct, Kategori kategori, String nameProduct, BigDecimal price, String filename, byte[] filedata) {
        this.idProduct = idProduct;
        this.kategori = kategori;
        this.nameProduct = nameProduct;
        this.price = price;
        this.filename = filename;
        this.filedata = filedata;
    }
    public Product(String idProduct, Kategori kategori, String nameProduct, BigDecimal price, String filename, byte[] filedata, Set<OrdersDetail> ordersDetails) {
       this.idProduct = idProduct;
       this.kategori = kategori;
       this.nameProduct = nameProduct;
       this.price = price;
       this.filename = filename;
       this.filedata = filedata;
       this.ordersDetails = ordersDetails;
    }
   
     @Id 

    
    @Column(name="id_product", unique=true, nullable=false, length=12)
    public String getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_kategori", nullable=false)
    public Kategori getKategori() {
        return this.kategori;
    }
    
    public void setKategori(Kategori kategori) {
        this.kategori = kategori;
    }

    
    @Column(name="name_product", nullable=false, length=100)
    public String getNameProduct() {
        return this.nameProduct;
    }
    
    public void setNameProduct(String nameProduct) {
        this.nameProduct = nameProduct;
    }

    
    @Column(name="price", nullable=false, precision=6, scale=3)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="filename", nullable=false, length=130)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="filedata", nullable=false)
    public byte[] getFiledata() {
        return this.filedata;
    }
    
    public void setFiledata(byte[] filedata) {
        this.filedata = filedata;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrdersDetail> getOrdersDetails() {
        return this.ordersDetails;
    }
    
    public void setOrdersDetails(Set<OrdersDetail> ordersDetails) {
        this.ordersDetails = ordersDetails;
    }




}


